import{S as c,i as a}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function u(i){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"43047953-84179c8300fd9f33658a206cf",q:i,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(s).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const m=document.querySelector("ul.gallery");function f(i){if(i.length==0)iziToast.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const o=i.map(t=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${t.largeImageURL}">
        <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
        </ul>
        </li>`).join("");m.insertAdjacentHTML("beforeend",o),new c("ul.gallery a",{captionsData:"alt"}).refresh()}}const p=document.querySelector("input"),d=document.querySelector("form"),l=document.querySelector(".loader"),h=document.querySelector("ul.gallery");d.addEventListener("submit",g);function g(i){i.preventDefault(),h.innerHTML="";const o=p.value.trim();o===""&&(l.classList.add("is-hidden"),a.error({color:"yellow",message:" Please fill in the field for search",position:"topRight"})),o&&(l.classList.remove("is-hidden"),u(o).then(s=>f(s.hits)).catch(s=>{console.log(s),a.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}))}
//# sourceMappingURL=commonHelpers.js.map
